version: '3'

services:
  database:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: app_database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
