version: '3.1'

services:
  app:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}

      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
    volumes:
      - ./:/app

  app_database:
    image: postgres:14.5-alpine
    container_name: app_database
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
